project_name: microservices-demo
domain: microservices.local

services:
  - name: frontend
    container_name: microservices_frontend
    build: ./frontend
    ports:
      - "80"
    environment:
      - API_GATEWAY_URL=http://gateway:8080
      - NODE_ENV=production
    depends_on:
      - gateway

  - name: gateway
    container_name: microservices_gateway
    build: ./gateway  
    ports:
      - "8080"
    environment:
      - USER_SERVICE_URL=http://user-service:3001
      - ORDER_SERVICE_URL=http://order-service:3002
      - PRODUCT_SERVICE_URL=http://product-service:3003
      - NOTIFICATION_SERVICE_URL=http://notification-service:3004
    depends_on:
      - user-service
      - order-service
      - product-service
      - notification-service

  - name: user-service
    container_name: microservices_user_service
    build: ./services/user-service
    ports:
      - "3001"
    environment:
      - DATABASE_URL=postgresql://user:password@user-db:5432/users
      - REDIS_URL=redis://redis:6379
    depends_on:
      - user-db
      - redis

  - name: order-service
    container_name: microservices_order_service
    build: ./services/order-service
    ports:
      - "3002"
    environment:
      - DATABASE_URL=postgresql://user:password@order-db:5432/orders
      - USER_SERVICE_URL=http://user-service:3001
      - PRODUCT_SERVICE_URL=http://product-service:3003
      - NOTIFICATION_SERVICE_URL=http://notification-service:3004
    depends_on:
      - order-db

  - name: product-service
    container_name: microservices_product_service
    build: ./services/product-service
    ports:
      - "3003"
    environment:
      - DATABASE_URL=postgresql://user:password@product-db:5432/products
      - REDIS_URL=redis://redis:6379
    depends_on:
      - product-db
      - redis

  - name: notification-service
    container_name: microservices_notification_service
    build: ./services/notification-service
    ports:
      - "3004"
    environment:
      - REDIS_URL=redis://redis:6379
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
    depends_on:
      - redis
      - mailhog

  - name: user-db
    container_name: microservices_user_db
    image: postgres:15-alpine
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=users
    volumes:
      - user_db_data:/var/lib/postgresql/data

  - name: order-db
    container_name: microservices_order_db
    image: postgres:15-alpine
    ports:
      - "5433"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=orders
    volumes:
      - order_db_data:/var/lib/postgresql/data

  - name: product-db
    container_name: microservices_product_db
    image: postgres:15-alpine
    ports:
      - "5434"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=products
    volumes:
      - product_db_data:/var/lib/postgresql/data

  - name: redis
    container_name: microservices_redis
    image: redis:7-alpine
    ports:
      - "6379"
    volumes:
      - redis_data:/data

  - name: mailhog
    container_name: microservices_mailhog
    image: mailhog/mailhog:latest
    ports:
      - "8025"  # Web UI
      - "1025"  # SMTP

volumes:
  user_db_data:
  order_db_data:
  product_db_data:
  redis_data:
