"""Handle generation of a *Caddyfile* and start/stop a Caddy container.

The Caddy reverse-proxy is optional and only required when TLS is enabled or
when sub-domain routing is desired. We run it in its own container so that the
host system does not need to have Caddy installed.
"""
from __future__ import annotations

import subprocess
from pathlib import Path
from typing import Dict, List, Any

import docker
from jinja2 import Template

__all__ = ["CaddyConfig"]

CADDYFILE_TEMPLATE = """
# Dynamic Caddyfile generated by DynaDock – do not edit manually ⚠️

{
    email admin@{{ domain }}
    {% if not enable_tls %}
    auto_https off
    {% endif %}
}

# Health endpoint on port 80 (always plain HTTP)
:80 {
    respond /health "OK" 200
}

{% if enable_tls %}
:443 {
    tls internal
}
{% endif %}

{% for service, port in services.items() %}
# ------------------------------
# Service: {{ service }}    ({{ port }})
# ------------------------------
{{ service }}.{{ domain }} {
    {% if enable_tls %}
    tls internal
    {% endif %}

    header {
        Access-Control-Allow-Origin "{{ cors_origins|join(', ') }}"
        Access-Control-Allow-Methods "GET,POST,PUT,DELETE,OPTIONS,PATCH"
        Access-Control-Allow-Headers "*"
        Access-Control-Allow-Credentials "true"
        Access-Control-Max-Age "3600"
    }

    @options method OPTIONS
    respond @options 204

    reverse_proxy localhost:{{ port }}

    log {
        output file /var/log/caddy/{{ service }}.log
        format json
        level info
    }
}
{% endfor %}
"""


class CaddyConfig:
    """Generate *Caddyfile* and manage the Caddy container."""

    _CONTAINER_NAME = "dynadock-caddy"

    def __init__(self, project_dir: Path):
        self.project_dir = Path(project_dir).resolve()
        self.caddy_dir = self.project_dir / ".dynadock" / "caddy"
        self.caddy_dir.mkdir(parents=True, exist_ok=True)
        self.client = docker.from_env()

    def generate(
        self,
        services: Dict[str, Any],
        ports: Dict[str, int],
        domain: str,
        enable_tls: bool,
        cors_origins: List[str],
    ) -> Path:
        """Render the full Caddyfile template."""
        template = Template(CADDYFILE_TEMPLATE)
        caddyfile_content = template.render(
            domain=domain,
            enable_tls=enable_tls,
            services=ports,
            cors_origins=cors_origins or [
                "http://localhost:3000",
                "http://localhost:5173",
                f"https://*.{domain}",
            ],
        )
        caddyfile_path = self.caddy_dir / "Caddyfile"
        with caddyfile_path.open("w", encoding="utf-8") as fp:
            fp.write(caddyfile_content)
        for sub in ("data", "config", "logs"):
            (self.caddy_dir / sub).mkdir(exist_ok=True)
        return caddyfile_path

    def generate_minimal(self) -> Path:
        """Generate a minimal Caddyfile to start the container."""
        caddyfile_content = "# Minimal Caddyfile for DynaDock startup"
        caddyfile_path = self.caddy_dir / "Caddyfile"
        with caddyfile_path.open("w", encoding="utf-8") as fp:
            fp.write(caddyfile_content)
        for sub in ("data", "config", "logs"):
            (self.caddy_dir / sub).mkdir(exist_ok=True)
        return caddyfile_path

    def is_running(self) -> bool:
        """Check if the Caddy container is running."""
        try:
            container = self.client.containers.get(self._CONTAINER_NAME)
            return container.status == "running"
        except docker.errors.NotFound:
            return False

    def start_caddy(self) -> None:
        """Start the Caddy container if it is not already running."""
        if self.is_running():
            return

        self.stop_caddy()  # Ensure any stopped containers are removed

        cmd = [
            "docker", "run", "-d",
            "--name", self._CONTAINER_NAME,
            "-p", "80:80",
            "-p", "443:443",
            "-p", "2019:2019",
            "-v", f"{self.caddy_dir}:/etc/caddy",
            "-v", f"{self.caddy_dir}/data:/data",
            "-v", f"{self.caddy_dir}/logs:/var/log/caddy",
            "caddy:2-alpine",
            "caddy", "run", "--config", "/etc/caddy/Caddyfile",
        ]
        subprocess.run(cmd, check=True, capture_output=True)

    def reload_caddy(self) -> None:
        """Reload the Caddy configuration in a running container."""
        if not self.is_running():
            return

        cmd = [
            "docker", "exec", self._CONTAINER_NAME,
            "caddy", "reload", "--config", "/etc/caddy/Caddyfile",
        ]
        subprocess.run(cmd, check=True, capture_output=True)

    def stop_caddy(self) -> None:
        """Stop and remove the Caddy container if it exists."""
        try:
            container = self.client.containers.get(self._CONTAINER_NAME)
            container.remove(force=True)
        except docker.errors.NotFound:
            pass
